#!/bin/sh
set -o errexit
set -o nounset

LD_FLAGS='-s -w'
PACK=true
if [ "$(uname)" = "Darwin" ]; then
    LD_FLAGS='-s -w -extldflags=-Wl,-no_warn_duplicate_libraries'
    PACK=false
fi

go env -w CGO_ENABLED=1 && govulncheck ./... && go vet ./... && golangci-lint run --timeout=5m && go clean -testcache && go test -tags="rgfw" -race ./... && go build -tags="rgfw" -ldflags="$LD_FLAGS" && strip blue && if [ "$PACK" = true ]; then upx blue; fi && cp blue ~/.blue/bin/ && ./gen-man.sh && sudo mkdir -p /usr/local/man/man1 && sudo cp man/blue.1 /usr/local/man/man1

# Build the minimal runner template next to blue so `blue pack` can find it
# (see cmd/bluerun and package binc).
go build -tags="minivm,rgfw" -ldflags="$LD_FLAGS" -o "bluerun-$(go env GOOS)-$(go env GOARCH)" ./cmd/bluerun
