#!/bin/sh
set -o errexit
set -o nounset

LD_FLAGS='-s -w'
PACK=true
if [ "$(uname)" = "Darwin" ]; then
    LD_FLAGS='-s -w -extldflags=-Wl,-no_warn_duplicate_libraries'
    PACK=false
fi

go env -w CGO_ENABLED=1 && govulncheck ./... && go clean -testcache && go test -race ./... && go build -ldflags="$LD_FLAGS" && strip blue && if [ "$PACK" = true ]; then upx blue; fi && cp blue ~/.blue/bin/ && ./gen-man.sh && sudo mkdir -p /usr/local/man/man1 && sudo cp man/blue.1 /usr/local/man/man1
