//go:build !static
// +build !static

package evaluator

import (
	"blue/lib"
	"blue/object"
)

func init() {
	_std_mods["ui"] = StdModFileAndBuiltins{File: lib.ReadStdFileToString("ui.b"), Builtins: _ui_builtin_map}
	_std_mods["gg"] = StdModFileAndBuiltins{File: lib.ReadStdFileToString("gg.b"), Builtins: _gg_builtin_map}
}

func setupBuiltinsWithEvaluator(name string, newE *Evaluator) {
	switch name {
	case "http":
		_http_builtin_map.Put("_handle", createHttpHandleBuiltin(newE, false))
		_http_builtin_map.Put("_handle_use", createHttpHandleBuiltin(newE, true))
		_http_builtin_map.Put("_handle_ws", createHttpHandleWSBuiltin(newE))
	case "ui":
		_ui_builtin_map.Put("_button", createUIButtonBuiltin(newE))
		_ui_builtin_map.Put("_check_box", createUICheckBoxBuiltin(newE))
		_ui_builtin_map.Put("_radio_group", createUIRadioBuiltin(newE))
		_ui_builtin_map.Put("_option_select", createUIOptionSelectBuiltin(newE))
		_ui_builtin_map.Put("_form", createUIFormBuiltin(newE))
		_ui_builtin_map.Put("_toolbar_action", createUIToolbarAction(newE))
	}
}

var _gg_builtin_map = NewBuiltinObjMap(BuiltinMapTypeInternal{
	"_init_window":               object.GetBuiltinByName(object.BuiltinGgType, "_init_window"),
	"_close_window":              object.GetBuiltinByName(object.BuiltinGgType, "_close_window"),
	"_window_should_close":       object.GetBuiltinByName(object.BuiltinGgType, "_window_should_close"),
	"_get_screen_width":          object.GetBuiltinByName(object.BuiltinGgType, "_get_screen_width"),
	"_get_screen_height":         object.GetBuiltinByName(object.BuiltinGgType, "_get_screen_height"),
	"_begin_drawing":             object.GetBuiltinByName(object.BuiltinGgType, "_begin_drawing"),
	"_end_drawing":               object.GetBuiltinByName(object.BuiltinGgType, "_end_drawing"),
	"_clear_background":          object.GetBuiltinByName(object.BuiltinGgType, "_clear_background"),
	"_color_map":                 object.GetBuiltinByName(object.BuiltinGgType, "_color_map"),
	"_draw_text":                 object.GetBuiltinByName(object.BuiltinGgType, "_draw_text"),
	"_draw_texture":              object.GetBuiltinByName(object.BuiltinGgType, "_draw_texture"),
	"_draw_texture_pro":          object.GetBuiltinByName(object.BuiltinGgType, "_draw_texture_pro"),
	"_draw_rectangle":            object.GetBuiltinByName(object.BuiltinGgType, "_draw_rectangle"),
	"_set_target_fps":            object.GetBuiltinByName(object.BuiltinGgType, "_set_target_fps"),
	"_set_exit_key":              object.GetBuiltinByName(object.BuiltinGgType, "_set_exit_key"),
	"_is_key_up":                 object.GetBuiltinByName(object.BuiltinGgType, "_is_key_up"),
	"_is_key_down":               object.GetBuiltinByName(object.BuiltinGgType, "_is_key_down"),
	"_is_key_pressed":            object.GetBuiltinByName(object.BuiltinGgType, "_is_key_pressed"),
	"_is_key_released":           object.GetBuiltinByName(object.BuiltinGgType, "_is_key_released"),
	"_load_texture":              object.GetBuiltinByName(object.BuiltinGgType, "_load_texture"),
	"_rectangle":                 object.GetBuiltinByName(object.BuiltinGgType, "_rectangle"),
	"_rectangle_check_collision": object.GetBuiltinByName(object.BuiltinGgType, "_rectangle_check_collision"),
	"_vector2":                   object.GetBuiltinByName(object.BuiltinGgType, "_vector2"),
	"_vector3":                   object.GetBuiltinByName(object.BuiltinGgType, "_vector3"),
	"_vector4":                   object.GetBuiltinByName(object.BuiltinGgType, "_vector4"),
	"_camera2d":                  object.GetBuiltinByName(object.BuiltinGgType, "_camera2d"),
	"_begin_mode2d":              object.GetBuiltinByName(object.BuiltinGgType, "_begin_mode2d"),
	"_end_mode2d":                object.GetBuiltinByName(object.BuiltinGgType, "_end_mode2d"),
	"_camera3d":                  object.GetBuiltinByName(object.BuiltinGgType, "_camera3d"),
	"_begin_mode3d":              object.GetBuiltinByName(object.BuiltinGgType, "_begin_mode3d"),
	"_end_mode3d":                object.GetBuiltinByName(object.BuiltinGgType, "_end_mode3d"),
	"_init_audio_device":         object.GetBuiltinByName(object.BuiltinGgType, "_init_audio_device"),
	"_close_audio_device":        object.GetBuiltinByName(object.BuiltinGgType, "_close_audio_device"),
	"_load_music":                object.GetBuiltinByName(object.BuiltinGgType, "_load_music"),
	"_update_music":              object.GetBuiltinByName(object.BuiltinGgType, "_update_music"),
	"_play_music":                object.GetBuiltinByName(object.BuiltinGgType, "_play_music"),
	"_stop_music":                object.GetBuiltinByName(object.BuiltinGgType, "_stop_music"),
	"_resume_music":              object.GetBuiltinByName(object.BuiltinGgType, "_resume_music"),
	"_pause_music":               object.GetBuiltinByName(object.BuiltinGgType, "_pause_music"),
	"_load_sound":                object.GetBuiltinByName(object.BuiltinGgType, "_load_sound"),
	"_play_sound":                object.GetBuiltinByName(object.BuiltinGgType, "_play_sound"),
	"_stop_sound":                object.GetBuiltinByName(object.BuiltinGgType, "_stop_sound"),
	"_resume_sound":              object.GetBuiltinByName(object.BuiltinGgType, "_resume_sound"),
	"_pause_sound":               object.GetBuiltinByName(object.BuiltinGgType, "_pause_sound"),
	"_unload":                    object.GetBuiltinByName(object.BuiltinGgType, "_unload"),
})

var _ui_builtin_map = NewBuiltinObjMap(BuiltinMapTypeInternal{
	"_new_app":                   object.GetBuiltinByName(object.BuiltinUiType, "_new_app"),
	"_window":                    object.GetBuiltinByName(object.BuiltinUiType, "_window"),
	"_label":                     object.GetBuiltinByName(object.BuiltinUiType, "_label"),
	"_progress_bar":              object.GetBuiltinByName(object.BuiltinUiType, "_progress_bar"),
	"_progress_bar_set_value":    object.GetBuiltinByName(object.BuiltinUiType, "_progress_bar_set_value"),
	"_toolbar":                   object.GetBuiltinByName(object.BuiltinUiType, "_toolbar"),
	"_toolbar_spacer":            object.GetBuiltinByName(object.BuiltinUiType, "_toolbar_spacer"),
	"_toolbar_separator":         object.GetBuiltinByName(object.BuiltinUiType, "_toolbar_separator"),
	"_row":                       object.GetBuiltinByName(object.BuiltinUiType, "_row"),
	"_col":                       object.GetBuiltinByName(object.BuiltinUiType, "_col"),
	"_grid":                      object.GetBuiltinByName(object.BuiltinUiType, "_grid"),
	"_entry":                     object.GetBuiltinByName(object.BuiltinUiType, "_entry"),
	"_entry_get_text":            object.GetBuiltinByName(object.BuiltinUiType, "_entry_get_text"),
	"_entry_set_text":            object.GetBuiltinByName(object.BuiltinUiType, "_entry_set_text"),
	"_append_form":               object.GetBuiltinByName(object.BuiltinUiType, "_append_form"),
	"_icon_account":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_account"),
	"_icon_cancel":               object.GetBuiltinByName(object.BuiltinUiType, "_icon_cancel"),
	"_icon_check_button_checked": object.GetBuiltinByName(object.BuiltinUiType, "_icon_check_button_checked"),
	"_icon_check_button":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_check_button"),
	"_icon_color_achromatic":     object.GetBuiltinByName(object.BuiltinUiType, "_icon_color_achromatic"),
	"_icon_color_chromatic":      object.GetBuiltinByName(object.BuiltinUiType, "_icon_color_chromatic"),
	"_icon_color_palette":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_color_palette"),
	"_icon_computer":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_computer"),
	"_icon_confirm":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_confirm"),
	"_icon_content_add":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_add"),
	"_icon_content_clear":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_clear"),
	"_icon_content_copy":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_copy"),
	"_icon_content_cut":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_cut"),
	"_icon_content_paste":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_paste"),
	"_icon_content_redo":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_redo"),
	"_icon_content_remove":       object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_remove"),
	"_icon_content_undo":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_content_undo"),
	"_icon_delete":               object.GetBuiltinByName(object.BuiltinUiType, "_icon_delete"),
	"_icon_document_create":      object.GetBuiltinByName(object.BuiltinUiType, "_icon_document_create"),
	"_icon_document":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_document"),
	"_icon_document_print":       object.GetBuiltinByName(object.BuiltinUiType, "_icon_document_print"),
	"_icon_document_save":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_document_save"),
	"_icon_download":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_download"),
	"_icon_error":                object.GetBuiltinByName(object.BuiltinUiType, "_icon_error"),
	"_icon_file_application":     object.GetBuiltinByName(object.BuiltinUiType, "_icon_file_application"),
	"_icon_file_audio":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_file_audio"),
	"_icon_file":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_file"),
	"_icon_file_image":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_file_image"),
	"_icon_file_text":            object.GetBuiltinByName(object.BuiltinUiType, "_icon_file_text"),
	"_icon_file_video":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_file_video"),
	"_icon_folder":               object.GetBuiltinByName(object.BuiltinUiType, "_icon_folder"),
	"_icon_folder_new":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_folder_new"),
	"_icon_folder_open":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_folder_open"),
	"_icon_grid":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_grid"),
	"_icon_help":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_help"),
	"_icon_history":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_history"),
	"_icon_home":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_home"),
	"_icon_info":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_info"),
	"_icon_list":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_list"),
	"_icon_login":                object.GetBuiltinByName(object.BuiltinUiType, "_icon_login"),
	"_icon_logout":               object.GetBuiltinByName(object.BuiltinUiType, "_icon_logout"),
	"_icon_mail_attachment":      object.GetBuiltinByName(object.BuiltinUiType, "_icon_mail_attachment"),
	"_icon_mail_compose":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_mail_compose"),
	"_icon_mail_forward":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_mail_forward"),
	"_icon_mail_reply_all":       object.GetBuiltinByName(object.BuiltinUiType, "_icon_mail_reply_all"),
	"_icon_mail_reply":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_mail_reply"),
	"_icon_mail_send":            object.GetBuiltinByName(object.BuiltinUiType, "_icon_mail_send"),
	"_icon_media_fast_forward":   object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_fast_forward"),
	"_icon_media_fast_rewind":    object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_fast_rewind"),
	"_icon_media_music":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_music"),
	"_icon_media_pause":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_pause"),
	"_icon_media_photo":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_photo"),
	"_icon_media_play":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_play"),
	"_icon_media_record":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_record"),
	"_icon_media_replay":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_replay"),
	"_icon_media_skip_next":      object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_skip_next"),
	"_icon_media_skip_previous":  object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_skip_previous"),
	"_icon_media_stop":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_stop"),
	"_icon_media_video":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_media_video"),
	"_icon_menu_drop_down":       object.GetBuiltinByName(object.BuiltinUiType, "_icon_menu_drop_down"),
	"_icon_menu_drop_up":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_menu_drop_up"),
	"_icon_menu_expand":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_menu_expand"),
	"_icon_menu":                 object.GetBuiltinByName(object.BuiltinUiType, "_icon_menu"),
	"_icon_more_horizontal":      object.GetBuiltinByName(object.BuiltinUiType, "_icon_more_horizontal"),
	"_icon_more_vertical":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_more_vertical"),
	"_icon_move_down":            object.GetBuiltinByName(object.BuiltinUiType, "_icon_move_down"),
	"_icon_move_up":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_move_up"),
	"_icon_navigate_back":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_navigate_back"),
	"_icon_navigate_next":        object.GetBuiltinByName(object.BuiltinUiType, "_icon_navigate_next"),
	"_icon_question":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_question"),
	"_icon_radio_button_checked": object.GetBuiltinByName(object.BuiltinUiType, "_icon_radio_button_checked"),
	"_icon_radio_button":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_radio_button"),
	"_icon_search":               object.GetBuiltinByName(object.BuiltinUiType, "_icon_search"),
	"_icon_search_replace":       object.GetBuiltinByName(object.BuiltinUiType, "_icon_search_replace"),
	"_icon_settings":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_settings"),
	"_icon_storage":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_storage"),
	"_icon_upload":               object.GetBuiltinByName(object.BuiltinUiType, "_icon_upload"),
	"_icon_view_full_screen":     object.GetBuiltinByName(object.BuiltinUiType, "_icon_view_full_screen"),
	"_icon_view_refresh":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_view_refresh"),
	"_icon_view_restore":         object.GetBuiltinByName(object.BuiltinUiType, "_icon_view_restore"),
	"_icon_visibility":           object.GetBuiltinByName(object.BuiltinUiType, "_icon_visibility"),
	"_icon_visibility_off":       object.GetBuiltinByName(object.BuiltinUiType, "_icon_visibility_off"),
	"_icon_volume_down":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_volume_down"),
	"_icon_volume_mute":          object.GetBuiltinByName(object.BuiltinUiType, "_icon_volume_mute"),
	"_icon_volume_up":            object.GetBuiltinByName(object.BuiltinUiType, "_icon_volume_up"),
	"_icon_warning":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_warning"),
	"_icon_zoom_fit":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_zoom_fit"),
	"_icon_zoom_in":              object.GetBuiltinByName(object.BuiltinUiType, "_icon_zoom_in"),
	"_icon_zoom_out":             object.GetBuiltinByName(object.BuiltinUiType, "_icon_zoom_out"),
})
