// Code generated by command: go run main.go -out ../../gemm_microkernel_amd64.s -stubs ../../gemm_microkernel_stub_amd64.go -pkg cpu. DO NOT EDIT.

//go:build amd64 && !goexperiment.simd

#include "textflag.h"

// func gemmMicroKernel6x16AVX2(c []float32, a []float32, b []float32, k int, cStride int)
// Requires: AVX, FMA3
TEXT ·gemmMicroKernel6x16AVX2(SB), NOSPLIT, $0-88
	MOVQ   c_base+0(FP), AX
	MOVQ   a_base+24(FP), CX
	MOVQ   b_base+48(FP), DX
	MOVQ   k+72(FP), BX
	MOVQ   cStride+80(FP), SI
	SHLQ   $0x02, SI
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
	VXORPS Y4, Y4, Y4
	VXORPS Y5, Y5, Y5
	VXORPS Y6, Y6, Y6
	VXORPS Y7, Y7, Y7
	VXORPS Y8, Y8, Y8
	VXORPS Y9, Y9, Y9
	VXORPS Y10, Y10, Y10
	VXORPS Y11, Y11, Y11

kloop6:
	CMPQ         BX, $0x00
	JE           kdone6
	VMOVUPS      (DX), Y12
	VMOVUPS      32(DX), Y13
	VBROADCASTSS (CX), Y14
	VFMADD231PS  Y12, Y14, Y0
	VFMADD231PS  Y13, Y14, Y1
	VBROADCASTSS 4(CX), Y14
	VFMADD231PS  Y12, Y14, Y2
	VFMADD231PS  Y13, Y14, Y3
	VBROADCASTSS 8(CX), Y14
	VFMADD231PS  Y12, Y14, Y4
	VFMADD231PS  Y13, Y14, Y5
	VBROADCASTSS 12(CX), Y14
	VFMADD231PS  Y12, Y14, Y6
	VFMADD231PS  Y13, Y14, Y7
	VBROADCASTSS 16(CX), Y14
	VFMADD231PS  Y12, Y14, Y8
	VFMADD231PS  Y13, Y14, Y9
	VBROADCASTSS 20(CX), Y14
	VFMADD231PS  Y12, Y14, Y10
	VFMADD231PS  Y13, Y14, Y11
	ADDQ         $0x18, CX
	ADDQ         $0x40, DX
	DECQ         BX
	JMP          kloop6

kdone6:
	VMOVUPS Y0, (AX)
	VMOVUPS Y1, 32(AX)
	ADDQ    SI, AX
	VMOVUPS Y2, (AX)
	VMOVUPS Y3, 32(AX)
	ADDQ    SI, AX
	VMOVUPS Y4, (AX)
	VMOVUPS Y5, 32(AX)
	ADDQ    SI, AX
	VMOVUPS Y6, (AX)
	VMOVUPS Y7, 32(AX)
	ADDQ    SI, AX
	VMOVUPS Y8, (AX)
	VMOVUPS Y9, 32(AX)
	ADDQ    SI, AX
	VMOVUPS Y10, (AX)
	VMOVUPS Y11, 32(AX)
	VZEROUPPER
	RET

// func gemmMicroKernel1x16AVX2(c []float32, a []float32, b []float32, k int)
// Requires: AVX, FMA3
TEXT ·gemmMicroKernel1x16AVX2(SB), NOSPLIT, $0-80
	MOVQ   c_base+0(FP), AX
	MOVQ   a_base+24(FP), CX
	MOVQ   b_base+48(FP), DX
	MOVQ   k+72(FP), BX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1

kloop1:
	CMPQ         BX, $0x00
	JE           kdone1
	VBROADCASTSS (CX), Y2
	VMOVUPS      (DX), Y3
	VMOVUPS      32(DX), Y4
	VFMADD231PS  Y3, Y2, Y0
	VFMADD231PS  Y4, Y2, Y1
	ADDQ         $0x04, CX
	ADDQ         $0x40, DX
	DECQ         BX
	JMP          kloop1

kdone1:
	VMOVUPS Y0, (AX)
	VMOVUPS Y1, 32(AX)
	VZEROUPPER
	RET

// func gemmMicroKernel1x16StridedAVX2(c []float32, a []float32, b []float32, k int, n int)
// Requires: AVX, FMA3
TEXT ·gemmMicroKernel1x16StridedAVX2(SB), NOSPLIT, $0-88
	MOVQ   c_base+0(FP), AX
	MOVQ   a_base+24(FP), CX
	MOVQ   b_base+48(FP), DX
	MOVQ   k+72(FP), BX
	MOVQ   n+80(FP), SI
	SHLQ   $0x02, SI
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1

kloop1s:
	CMPQ         BX, $0x00
	JE           kdone1s
	VBROADCASTSS (CX), Y2
	VMOVUPS      (DX), Y3
	VMOVUPS      32(DX), Y4
	VFMADD231PS  Y3, Y2, Y0
	VFMADD231PS  Y4, Y2, Y1
	ADDQ         $0x04, CX
	ADDQ         SI, DX
	DECQ         BX
	JMP          kloop1s

kdone1s:
	VMOVUPS Y0, (AX)
	VMOVUPS Y1, 32(AX)
	VZEROUPPER
	RET
