// Code generated by command: go run main.go -out ../../gemm_microkernel_amd64.s -stubs ../../gemm_microkernel_stub_amd64.go -pkg cpu. DO NOT EDIT.

//go:build amd64 && !goexperiment.simd

package cpu

// gemmMicroKernel6x16AVX2 computes a 6x16 tile C[r,col] = sum_kk a[kk*6+r]*b[kk*16+col]
// (overwriting C) from PACKED panels a ([k][6]) and b ([k][16]), holding all 12 YMM
// accumulators in registers across the k-loop. cStride is the C row stride in elements.
//
//go:noescape
func gemmMicroKernel6x16AVX2(c []float32, a []float32, b []float32, k int, cStride int)

// gemmMicroKernel1x16AVX2 computes a 1x16 tile C[0,col] = sum_kk a[kk]*b[kk*16+col]
// (overwriting C) from an unpacked source row a ([k]) and the packed B panel b ([k][16]),
// with the two C accumulators held in registers across the k-loop.
//
//go:noescape
func gemmMicroKernel1x16AVX2(c []float32, a []float32, b []float32, k int)

// gemmMicroKernel1x16StridedAVX2 computes a 1x16 tile C[0,col] = sum_kk a[kk]*b[kk*n+col]
// (overwriting C) reading B with its native row stride n (unpacked). Used for GEMV / thin
// shapes where packing B would not pay off. c and a are tile-local; n is the B row stride.
//
//go:noescape
func gemmMicroKernel1x16StridedAVX2(c []float32, a []float32, b []float32, k int, n int)
