// Code generated by command: go run main.go -out ../../depthwise_simd_amd64.s -stubs ../../depthwise_simd_stub_gen_amd64.go -pkg operators. DO NOT EDIT.

package operators

// depthwise3x3PlaneAVX2 computes one stride=1, padding=0 3x3 depthwise plane:
// out[oh*wOut+j..] = sum over the nine taps of weight[k]*in[(oh+kh)*wp + j+kw ..],
// for the first w8 (multiple of 8) output columns of each of hOut rows. The Go
// caller fills the sub-8 column tail and loops planes.
//
//go:noescape
func depthwise3x3PlaneAVX2(out []float32, in []float32, weight []float32, wp int, wOut int, hOut int, w8 int)
