// Code generated by command: go run main.go -out ../../depthwise_simd_amd64.s -stubs ../../depthwise_simd_stub_gen_amd64.go -pkg operators. DO NOT EDIT.

#include "textflag.h"

// func depthwise3x3PlaneAVX2(out []float32, in []float32, weight []float32, wp int, wOut int, hOut int, w8 int)
// Requires: AVX, FMA3
TEXT ·depthwise3x3PlaneAVX2(SB), NOSPLIT, $0-104
	MOVQ         out_base+0(FP), AX
	MOVQ         in_base+24(FP), CX
	MOVQ         weight_base+48(FP), DX
	MOVQ         wp+72(FP), BX
	MOVQ         wOut+80(FP), SI
	MOVQ         hOut+88(FP), DI
	MOVQ         w8+96(FP), R8
	VBROADCASTSS (DX), Y0
	VBROADCASTSS 4(DX), Y1
	VBROADCASTSS 8(DX), Y2
	VBROADCASTSS 12(DX), Y3
	VBROADCASTSS 16(DX), Y4
	VBROADCASTSS 20(DX), Y5
	VBROADCASTSS 24(DX), Y6
	VBROADCASTSS 28(DX), Y7
	VBROADCASTSS 32(DX), Y8
	MOVQ         BX, DX
	SHLQ         $0x02, DX
	MOVQ         SI, BX
	SHLQ         $0x02, BX
	MOVQ         AX, AX
	MOVQ         DI, SI

rowLoop:
	CMPQ SI, $0x00
	JE   done
	MOVQ CX, DI
	LEAQ (CX)(DX*1), R9
	LEAQ (R9)(DX*1), R10
	MOVQ AX, R11
	MOVQ R8, R12
	SHRQ $0x03, R12

colLoop:
	CMPQ        R12, $0x00
	JE          colDone
	VMOVUPS     (DI), Y12
	VMULPS      Y12, Y0, Y9
	VMOVUPS     4(DI), Y12
	VFMADD231PS Y12, Y1, Y9
	VMOVUPS     8(DI), Y12
	VFMADD231PS Y12, Y2, Y9
	VMOVUPS     (R9), Y12
	VMULPS      Y12, Y3, Y10
	VMOVUPS     4(R9), Y12
	VFMADD231PS Y12, Y4, Y10
	VMOVUPS     8(R9), Y12
	VFMADD231PS Y12, Y5, Y10
	VMOVUPS     (R10), Y12
	VMULPS      Y12, Y6, Y11
	VMOVUPS     4(R10), Y12
	VFMADD231PS Y12, Y7, Y11
	VMOVUPS     8(R10), Y12
	VFMADD231PS Y12, Y8, Y11
	VADDPS      Y10, Y9, Y9
	VADDPS      Y11, Y9, Y9
	VMOVUPS     Y9, (R11)
	ADDQ        $0x20, DI
	ADDQ        $0x20, R9
	ADDQ        $0x20, R10
	ADDQ        $0x20, R11
	DECQ        R12
	JMP         colLoop

colDone:
	ADDQ DX, CX
	ADDQ BX, AX
	DECQ SI
	JMP  rowLoop

done:
	VZEROUPPER
	RET
