// Code generated by command: go run main.go -out ../../pow_simd_amd64.s -stubs ../../pow_simd_stub_gen_amd64.go -pkg operators. DO NOT EDIT.

package operators

// powConstF32AVX2 computes out[i] = pow(in[i], c) = exp(c*log(in[i])) for the
// first n (multiple of 8) float32 lanes using AVX2+FMA Cephes logf and expf.
// Non-positive inputs are flushed to 0. The caller handles any sub-8 remainder.
//
//go:noescape
func powConstF32AVX2(out []float32, in []float32, n int, c float32)
