name: Platform Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies Linux
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libwayland-dev libxkbcommon-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev bc
      if: ${{ runner.os == 'Linux' }}

    - name: Tests
      run: |
        go env -w CC=gcc-12
        go env -w CXX=g++-12
        gcc-12 --version
        go test -race -ldflags "-extld gcc -extldflags '-Wl,--allow-multiple-definition'" ./...
      if: ${{ runner.os == 'MacOS'}}

    - name: Tests
      run: go test -race -ldflags "-extld gcc -extldflags '-Wl,--allow-multiple-definition'" ./...
      if: ${{ runner.os != 'MacOS'}}
