name: Release
on: 
  push:
    tags:
    - 'v*.*.*'

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get dependencies for fyne
      run: sudo apt-get update && sudo apt-get install pkg-config gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libwayland-dev libxkbcommon-dev bc

    - uses: wangyoucao577/go-release-action@v1.32
      with:
        goversion: 1.19
        executable_compression: upx
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        ldflags: -s -w -extldflags="-static"
  release-windows-amd64:
    name: release windows/amd64
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - uses: wangyoucao577/go-release-action@v1.32
      with:
        goversion: 1.19
        executable_compression: upx
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64
        ldflags: -s -w -extldflags="-static" -H=windowsgui
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: wangyoucao577/go-release-action@v1.32
      with:
        goversion: 1.19
        executable_compression: upx
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: amd64
        ldflags: -s -w -extldflags="-static"